listener:
  serverPort: 80 # k8s probes, optional
  slotName: myslot_2
  refreshConnection: 30s
  heartbeatInterval: 10s
  filter:
    tables:
      ac_user: [insert, update, delete]
      ac_team: [insert, update, delete]
      ac_team_user: [insert, update, delete]
      ac_contract: [insert, update, delete]
      ac_cluster_info: [insert, update, delete]
  topicsMap:
    schema_table_name: "notifier"
logger:
  level: info
  fmt: json
database:
  host: 127.0.0.1:5432
  port: 5432
  name: outbox
  user: postgres
  password: postgres
  debug: false
publisher:
  type: nats
  address: localhost:30222
  natsAdminCredPath: /home/imtiazcho/go/src/go.bytebuilders.dev/launchpad/2021/gitea_setup/nats/admin.creds # nats only
  enableTLS: true # Kafka only
  clientCert: "cert.pem" # Kafka only
  clientKey: "key.pub" # Kafka only
  caCert: "ca.pem" # Kafka only
  topic: "outbox"
  topicPrefix: ""
monitoring:
  sentryDSN: ""
  promAddr: ":2112"